# config.py

MODE = "LIVE"       # "PAPER" or "LIVE"

SYMBOL = "BHARTIARTL-EQ"

QUANTITY = 35

EXCHANGE = "NSE"

PRODUCT_TYPE = "INTRADAY"

# Angel One (used only in LIVE mode)
API_KEY = "K9Fhvfho"

CLIENT_CODE = "AAAN998226"

PASSWORD = "3027"

TOTP_SECRET = "UA3PJRBKTOTUQSVH67Y4F5ZEZM"